apiVersion: v1
kind: Service
metadata:
  name: scale-street
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: scale-street
  ports:
    - name: http
      port: 80
      targetPort: http
